const MAX_HOSPITAL_VISITED = 3;
const MAX_DOCTOR_VISITED = 5;
const MAX_OBSERVATIONS = 10;
const DURATIONS = "10 months";

export {
  MAX_DOCTOR_VISITED,
  MAX_HOSPITAL_VISITED,
  MAX_OBSERVATIONS,
  DURATIONS,
};
